#! /bin/bash

echo "Hello World!"

hippo="bananas" #comment here

# echo $hippo

# playing with arguments
# these are for invidual arguments
echo $1
echo $0
# this gets all arguments
echo $@
# this get how many arguments
echo $#
